### ISSUE TITLE
Roadmap 0.0.1

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels-example-app#2]
## 0.0.1 - 06 Jun 2018

Initial Alpha Release

### User Management

- [x] Create, update & disable users
- [x] Assume user accounts
- [x] Disabled (soft deleted) users can then be deleted
- [x] Searchable/Filterable User Index
- [x] Add Optional User Registration
- [x] Add New Account email confirmation on registration

### Roles & Permissions

- [x] 3 Default roles: Admin, Editor, User
- [x] New roles can be added via web interface
- [x] Each role can have default permissions set
- [x] Automatic cascading Controller Based Permissions based on controller/action path
- [x] Add User Permissions
- [x] Permissions can be altered via web interface
- [x] Add Named Permissions

### Authentication

- [x] Tableless models used for Authentication 
- [x] "Local" user accounts are the default
- [x] This app uses session based authentication, session rotation and session invalidation
- [x] Sets Set Cache-Control: must-re-validate for authenticated pages
- [x] Sets HTTPOnly attribute on Cookies
- [x] "Remember Me" Cookie function

### Passwords

- [x] Passwords hashed via bCrypt (AuthenticateThis plugin)
- [x] Password reset feature / emails
- [x] Add Require password change on login

### Settings

- [x] Database based configuration and settings

### Logging

- [x] Add rudimentary logging for auditing activity
- [x] Automatic logging of changed properties on models
- [x] Facility to skip sensitive fields from automatic changed property logging
- [x] Add ability to store extended log data

### Other

- [x] Add Database Migrations 
- [x] Log Severity level
- [x] Add Gravatar support to users
