### ISSUE TITLE
Roadmap 0.0.2

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels-example-app#3]
## 0.0.2 20 Jun 2018

Second Alpha Release

### Bug Fixes
- [x] Email Validation on User Model now doesn't have duplicate errors
- [x] Basic ACF2016 compatibility

### Enhancements
- [x] Filter audit logs by date range via Date Range Picker JS
